### ISSUE TITLE
Unstable development builds - please read

### ISSUE THREAD

**Issue by TheBusyBiscuit** [Slimefun/SensibleToolbox#7]
# ❗ IMPORTANT
SensibleToolbox used to be discontinued in **Minecraft 1.9**.
But I recently have updated it to work on **Minecraft 1.14-1.16**, note though that these builds are extremely **UNSTABLE**.

To reiterate: They are not stable. We don't recommend using them on any live server yet, you should be careful and only ever use STB on a designated private test server for now.

Updating this project took me a total of **9 months** and it has only gotten to the point of being compilation-ready.
So now it comes to you, please test these builds and [report any bugs that arise](https://github.com/Slimefun/SensibleToolbox/issues). I am sure that together, we will revive this old fan-favourite.

## 📚 To Dos
STB is compileable now, but it is full of bugs and needs a lot of love and care.
Even the code needs to be updated, refactored in many many places too!

- [ ] Adding Javadocs to most main methods
- [ ] Adding `@author` tags retroactively to files to indicate who created them
- [ ] Adding `@Nonnull` and `@Nullable` annotations to method parameters and return types
- [ ] Clearing out all deprecation warnings
- [ ] Getting everything to work properly again and fixing all bugs

**Comment by ErythroCraft** [comment]
[20:40:31] [Server thread/INFO]: [SensibleToolbox] Enabling SensibleToolbox vDEV - 45 (git dbcee02b)
[20:40:31] [Server thread/INFO]: [SensibleToolbox] Connecting to local database...
[20:40:32] [Server thread/ERROR]: Error occurred while enabling SensibleToolbox vDEV - 45 (git dbcee02b) (Is it up to date?)
java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem
        at io.github.thebusybiscuit.sensibletoolbox.SensibleToolboxPlugin.onEnable(SensibleToolboxPlugin.java:263) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:3231-Spigot-3c1fc60-e167f28]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3231-Spigot-3c1fc60-e167f28]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3231-Spigot-3c1fc60-e167f28]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:511) ~[server.jar:3231-Spigot-3c1fc60-e167f28]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:425) ~[server.jar:3231-Spigot-3c1fc60-e167f28]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[server.jar:3231-Spigot-3c1fc60-e167f28]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[server.jar:3231-Spigot-3c1fc60-e167f28]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[server.jar:3231-Spigot-3c1fc60-e167f28]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[server.jar:3231-Spigot-3c1fc60-e167f28]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[server.jar:3231-Spigot-3c1fc60-e167f28]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[server.jar:3231-Spigot-3c1fc60-e167f28]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
